apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: "2022-06-06T16:04:55Z"
  generation: 1
  name: test-job
  namespace: hsbuilds
  resourceVersion: "2028953"
  uid: 34709a89-8ff7-4668-a92a-6f9a99a67096
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: test-job
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: default-route-openshift-image-registry.apps-crc.testing/hsbuilds/buildah2
            imagePullPolicy: Always
            name: test-job
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '*/1 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
status: {}
