FROM quay.io/centoshyperscale/centos:stream8

ENV _BUILDAH_STARTED_IN_USERNS="" \
    BUILDAH_ISOLATION=chroot \
    STORAGE_DRIVER=vfs

RUN adduser build #-g 0 -u 1001 build

RUN dnf -y update
RUN dnf -y install buildah python3-devel 
RUN dnf -y clean all && \
    rm -rf /var/cache /var/log/dnf* /var/log/yum.*

RUN chmod u-s /usr/bin/newuidmap && \
    chmod u-s /usr/bin/newgidmap 

RUN touch /etc/subgid /etc/subuid && \
    chmod g=u /etc/subgid /etc/subuid /etc/passwd && \
    echo build:10000:65536 > /etc/subuid && \
    echo build:10000:65536 > /etc/subgid

ADD https://raw.githubusercontent.com/containers/buildah/main/contrib/buildahimage/stable/containers.conf /etc/containers/containers.conf

RUN chmod 644 /etc/containers/containers.conf

RUN echo "export BUILDAH_ISOLATION=chroot" >> /home/build/.bashrc
RUN mkdir -p /home/build/.local/share/containers
RUN mkdir -p /home/build/.config/containers && \
    (echo '[storage]';echo 'driver = "vfs"') > /home/build/.config/containers/storage.conf

#ADD https://raw.githubusercontent.com/containers/podman/main/contrib/podmanimage/stable/podman-containers.conf /home/build/.config/containers/containers.conf
#RUN chmod 664 /home/build/.config/containers/containers.conf

#RUN chown -R build:0 /home/build && \
#    chmod -R 777 /home/build
RUN chown build:build -R /home/build

VOLUME /var/lib/containers
VOLUME /home/build/.local/share/containers

RUN mkdir -p /var/lib/shared/vfs-images \
             /var/lib/shared/vfs-layers && \
    touch /var/lib/shared/vfs-images/images.lock && \
    touch /var/lib/shared/vfs-layers/layers.lock

USER build
WORKDIR /home/build

CMD ["python3", "-m", "http.server"]
