FROM quay.io/centoshyperscale/centos:stream9

# from https://pagure.io/centos-sig-hyperscale/containers-releng/blob/main/f/Containerfile

RUN dnf -y update
RUN rpm --restore shadow-utils 2>/dev/null
RUN dnf -y install buildah fuse-overlayfs; rm -rf /var/cache /var/log/dnf* /var/log/yum.*
RUN dnf -y clean all

ADD https://raw.githubusercontent.com/containers/buildah/main/contrib/buildahimage/stable/containers.conf /etc/containers/

RUN chmod 644 /etc/containers/containers.conf; sed -i -e 's|^#mount_program|mount_program|g' -e '/additionalimage.*/a "/var/lib/shared",' -e 's|^mountopt[[:space:]]*=.*$|mountopt = "nodev,fsync=0"|g' /etc/containers/storage.conf
RUN mkdir -p /var/lib/shared/overlay-images /var/lib/shared/overlay-layers /var/lib/shared/vfs-images /var/lib/shared/vfs-layers; touch /var/lib/shared/overlay-images/images.lock; touch /var/lib/shared/overlay-layers/layers.lock; touch /var/lib/shared/vfs-images/images.lock; touch /var/lib/shared/vfs-layers/layers.lock

# Adjust storage.conf to enable Fuse storage.
#RUN sed -i /etc/containers/storage.conf \
#        -e 's|^#mount_program|mount_program|g' \
#        -e '/additionalimage.*/a "/var/lib/shared",'

#RUN mkdir -p /var/lib/shared/overlay-images /var/lib/shared/overlay-layers \
# && touch /var/lib/shared/overlay-images/images.lock \
#          /var/lib/shared/overlay-layers/layers.lock

ENV BUILDAH_ISOLATION=chroot

RUN echo build:2000:50000 > /etc/subuid \
 && echo build:2000:50000 > /etc/subgid

COPY build.sh build
COPY autobuild.sh autobuild

#RUN chgrp -R 0 $HOME && \
#         chmod -R g=u $HOME

RUN chmod +x build
RUN chmod +x autobuild

ENTRYPOINT ["./autobuild"]
CMD ["9"]

